# Generated by Django 6.0.2 on 2026-03-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutalk', '0005_alter_post_body_alter_post_user_group_post_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='rutalk.group'),
        ),
    ]
